### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [jeffmikels/ptz-server#6]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [VIDEO category](https://github.com/forart/HyMPS#-1) \ [Pan Tilt Zoom page](https://github.com/forart/HyMPS/blob/main/V_PTZ.md#--) \ [Generic subsection](https://github.com/forart/HyMPS/blob/main/V_PTZ.md#generic-)), can you please add the license to it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/jeffmikels/ptz-server/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/jeffmikels/ptz-server/?label=LICENSE)

Anyway you can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by forart** [comment]
Bump (request updated).

**Comment by jeffmikels** [comment]
Thanks for the reminder.
